.github/workflows/mypy.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, ctm/configs/ctm_config_base.py, ctm/processors/processor_bart_text_summary.py, ctm/processors/processor_base.py, ctm/processors/processor_gpt4.py, ctm/processors/processor_gpt4v.py, ctm/processors/processor_gpt4v_cloth_fashion.py, ctm/processors/processor_gpt4v_ocr.py, ctm/processors/processor_gpt4v_posture.py, ctm/processors/processor_gpt4v_scene_location.py, ctm/processors/processor_roberta_text_sentiment.py, ctm/utils/loader.py, stubs/huggingface_hub/__init__.pyi
=> re-support ctm example run

.pre-commit-config.yaml, ctm/messengers/messenger_bart_text_summ.py, ctm/messengers/messenger_base.py, ctm/messengers/messenger_gpt4v.py, ctm/messengers/messenger_roberta_text_sentiment.py, ctm/processors/processor_bart_text_summary.py, ctm/processors/processor_gpt4.py, ctm/processors/processor_gpt4_speaker_intent.py, ctm/processors/processor_gpt4_text_emotion.py, ctm/processors/processor_gpt4_text_summary.py, ctm/processors/processor_gpt4v.py, ctm/processors/processor_gpt4v_cloth_fashion.py, ctm/processors/processor_gpt4v_face_emotion.py, ctm/processors/processor_gpt4v_ocr.py, ctm/processors/processor_gpt4v_posture.py, ctm/processors/processor_gpt4v_scene_location.py, ctm/processors/processor_roberta_text_sentiment.py, ctm_conf/sarcasm_ctm_config.json
=> support messenger

.pre-commit-config.yaml, ctm/ctms/ctm_base.py, poetry.lock
=> fix none default group name bug

ctm/configs/ctm_config_base.py, ctm/ctms/ctm_base.py, ctm/processors/processor_base.py, ctm/scorers/__init__.py, ctm/scorers/scorer_base.py, ctm/scorers/scorer_gpt4.py, ctm/supervisors/supervisor_base.py, poetry.lock
=> split scorer as an independent component

ctm/ctms/ctm_base.py
=> support removing

ctm_ai/messengers/messenger_audio.py, ctm_ai/messengers/messenger_video.py, ctm_ai/messengers/messenger_vision.py
=> bug(processors): vision, audio, image processors only receive query

ctm_ai/executors/executor_language.py, ctm_ai/fusers/fuser_language.py, ctm_ai/scorers/scorer_language.py, ctm_ai/supervisors/supervisor_language.py
=> bug(src): change default LLM name

ctm_ai/executors/executor_language.py, ctm_ai/fusers/fuser_language.py, ctm_ai/scorers/scorer_language.py, ctm_ai/supervisors/supervisor_language.py, pyproject.toml
=> feat(poetry): prepare for the release of 0.0.1

README.md
=> bug(readme): fix a typo in readme

README.md, ctm_ai/executors/executor_search.py, poetry.lock, pyproject.toml
=> bug(processor) #191: search processor show the summary and title of the website

ctm_ai/chunks/chunk_manager.py, ctm_ai/ctms/ctm_base.py, ctm_ai/graphs/processor_graph.py
=> bug(graph): fix processors links

backend/app.py, backend/app_wrapper.py, frontend/src/App.js, frontend/src/utils/api.js, poetry.lock, pyproject.toml
=> fix(frontend): network error when submit from frontend

backend/app.py
=> fix(backend): not callable error fix

backend/Depolyment.md, backend/README.md, poetry.lock, pyproject.toml
=> doc(backend): add depolyment doc and readme for backend

backend/Depolyment.md, backend/README.md
=> fix(bakcend): update deployment doc

ctm_ai/executors/executor_audio.py, ctm_ai/executors/executor_video.py, ctm_ai/executors/executor_vision.py
=> fix(processors): return when no input audios, videos, pictures

backend/Depolyment.md
=> feat(doc): update aws Depolyment.md

backend/Depolyment.md
=> feat(backend): update aws Depolyment.md

ctm_ai/executors/executor_tool.py
=> fix(toolbench): fix tool error

backend/Depolyment.md
=> feat(doc): update deployment.md

backend/Depolyment.md
=> feat(deploy): add doc about socket

ctm_ai/executors/executor_audio.py, ctm_ai/executors/executor_base.py, ctm_ai/executors/executor_video.py, ctm_ai/utils/litellm_utils.py, ctm_conf/sarcasm_ctm_config.json, exp_mustard/run_ctm.py
=> fix(litellm): fix bugs of litellm

ctm_ai/apis/pipeline_runner.py, ctm_ai/ctms/ctm.py, ctm_ai/ctms/ctm_base.py, ctm_ai/processors/processor_base.py, ctm_ai/processors/processor_tool.py, ctm_conf/sarcasm_ctm_config.json, exp_mustard/prepare_input_files.py, exp_mustard/run_ctm.py, exp_toolbench/run_ctm.py
=> fix(toolbench): support full toolbench

ctm_ai/configs/ctm_config_base.py, ctm_ai/executors/executor_audio.py, ctm_ai/executors/executor_language.py, ctm_ai/executors/executor_video.py, ctm_ai/scorers/scorer_base.py, ctm_ai/supervisors/supervisor_language.py, ctm_conf/sarcasm_ctm_config.json, exp_mustard/run_ctm.py, exp_urfunny/data_raw/data_raw_download.txt, exp_urfunny/prepare_input_files.py, exp_urfunny/run_ctm.py
=> fix(exp): urfunny exp
